#ifndef INSOMNIA_USER_KEY_DEFS_H
#define INSOMNIA_USER_KEY_DEFS_H

#include "config.h"

#ifdef DOS
#define START_KEYBOARD_INTERRUPT() __asm__ __volatile__ ("pushal\n	pushw %ds\n	pushl %esi");
#define END_KEYBOARD_INTERRUPT() __asm__ __volatile__ ("inb $0x61, %al\n\torb $0x80, %al\n\toutb %al, $0x61\n\tandb $0x7f, %al\n\toutb %al, $0x61\n\tmovb $0x20, %al\n\toutb %al, $0x20\n\tpopl %esi\n\tpopw %ds\n\tpopal\n\tpopl %ebp\n\tsti\n\tiret");

#define KEY_ESC        0x01
#define KEY_1          0x02
#define KEY_2          0x03
#define KEY_3          0x04
#define KEY_4          0x05
#define KEY_5          0x06
#define KEY_6          0x07
#define KEY_7          0x08
#define KEY_8          0x09
#define KEY_9          0x0a
#define KEY_0          0x0b
#define KEY_MINUS      0x0c
#define KEY_EQUALS     0x0d
#define KEY_BACKSP     0x0e
#define KEY_TAB        0x0f
#define KEY_Q          0x10
#define KEY_W          0x11
#define KEY_E          0x12
#define KEY_R          0x13
#define KEY_T          0x14
#define KEY_Y          0x15
#define KEY_U          0x16
#define KEY_I          0x17
#define KEY_O          0x18
#define KEY_P          0x19
#define KEY_LBRAK      0x1a
#define KEY_RBRAK      0x1b
#define KEY_RETURN     0x1c
#define KEY_RCTRL      0x9d
#define KEY_LCTRL      0x1d
#define KEY_A          0x1e
#define KEY_S          0x1f
#define KEY_D          0x20
#define KEY_F          0x21
#define KEY_G          0x22
#define KEY_H          0x23
#define KEY_J          0x24
#define KEY_K          0x25
#define KEY_L          0x26
#define KEY_SCOLON     0x27
#define KEY_QUOTE      0x28
#define KEY_BQUOTE     0x29
#define KEY_TILDE      0x29
#define KEY_LSHIFT     0x2a
#define KEY_BSLASH     0x2b
#define KEY_Z          0x2c
#define KEY_X          0x2d
#define KEY_C          0x2e
#define KEY_V          0x2f
#define KEY_B          0x30
#define KEY_N          0x31
#define KEY_M          0x32
#define KEY_COMA       0x33
#define KEY_DOT        0x34
#define KEY_SLASH      0x35
#define KEY_GREY_SLASH 0xB5
#define KEY_RSHIFT     0x36
#define KEY_GREY_STAR  0x37
#define KEY_RALT       0xB8
#define KEY_LALT       0x38
#define KEY_SPACE      0x39
#define KEY_CAPS       0x3a
#define KEY_F1         0x3b
#define KEY_F2         0x3c
#define KEY_F3         0x3d
#define KEY_F4         0x3e
#define KEY_F5         0x3f
#define KEY_F6         0x40
#define KEY_F7         0x41
#define KEY_F8         0x42
#define KEY_F9         0x43
#define KEY_F10        0x44
#define KEY_NUMLOCK    0x45
#define KEY_SCRLOCK    0x46
#define KEY_HOME       0xc7
#define KEY_PAD_7      0x47
#define KEY_UP         0xc8
#define KEY_PAD_8      0x48
#define KEY_PGUP       0xc9
#define KEY_PAD_9      0x49
#define KEY_GREY_MINUS 0x4a
#define KEY_LEFT       0xcb
#define KEY_PAD_4      0x4b
#define KEY_PAD_5      0x4c
#define KEY_RIGHT      0xcd
#define KEY_PAD_6      0x4d
#define KEY_GREY_PLUS  0x4e
#define KEY_END        0xcf
#define KEY_PAD_1      0x4f
#define KEY_DOWN       0xd0
#define KEY_PAD_2      0x50
#define KEY_PGDN       0xd1
#define KEY_PAD_3      0x51
#define KEY_INSERT     0xd2
#define KEY_PAD_0      0x52
#define KEY_DEL        0xd3
#define KEY_PAD_DOT    0x53
#define KEY_ENTER      0x9c
#define KEY_F11        0x57
#define KEY_F12        0x58
#define KEY_PAUSE      0xC5
#endif

#ifdef X_WINDOWS
#include <X11/keysym.h>

#define KEY_ESC        XK_Escape
#define KEY_1          XK_1
#define KEY_2          XK_2
#define KEY_3          XK_3
#define KEY_4          XK_4
#define KEY_5          XK_5
#define KEY_6          XK_6
#define KEY_7          XK_7
#define KEY_8          XK_8
#define KEY_9          XK_9
#define KEY_0          XK_0
#define KEY_MINUS      XK_minus
#define KEY_EQUALS     XK_equal
#define KEY_BACKSP     XK_BackSpace
#define KEY_TAB        XK_Tab
#define KEY_Q          XK_q
#define KEY_W          XK_w
#define KEY_E          XK_e
#define KEY_R          XK_r
#define KEY_T          XK_t
#define KEY_Y          XK_y
#define KEY_U          XK_u
#define KEY_I          XK_i
#define KEY_O          XK_o
#define KEY_P          XK_p
#define KEY_TILDE      XK_tilde
#define KEY_BQUOTE     XK_quoteleft
#define KEY_QUOTE      XK_quoteright
#define KEY_RETURN     XK_Return
#define KEY_RCTRL      XK_Control_R
#define KEY_LCTRL      XK_Control_L
#define KEY_A          XK_a
#define KEY_S          XK_s
#define KEY_D          XK_d
#define KEY_F          XK_f
#define KEY_G          XK_g
#define KEY_H          XK_h
#define KEY_J          XK_j
#define KEY_K          XK_k
#define KEY_L          XK_l
#define KEY_SCOLON     XK_semicolon
#define KEY_LBRAK     XK_braketleft
#define KEY_RBRAK     XK_braketright
#define KEY_LSHIFT     XK_Shift_L
#define KEY_BSLASH     XK_backslash
#define KEY_Z          XK_z
#define KEY_X          XK_x
#define KEY_C          XK_c
#define KEY_V          XK_v
#define KEY_B          XK_b
#define KEY_N          XK_n
#define KEY_M          XK_m
#define KEY_COMA       XK_comma
#define KEY_DOT        XK_period
#define KEY_SLASH      XK_slash
#define KEY_RSHIFT     XK_Shift_R
#define KEY_GREY_STAR  XK_KP_Multiply
#define KEY_GREY_SLASH XK_KP_Divide
#define KEY_RALT        XK_Alt_R
#define KEY_LALT        XK_Alt_L
#define KEY_SPACE      XK_space
#define KEY_CAPS       XK_Caps_Lock
#define KEY_F1         XK_F1
#define KEY_F2         XK_F2
#define KEY_F3         XK_F3
#define KEY_F4         XK_F4
#define KEY_F5         XK_F5
#define KEY_F6         XK_F6
#define KEY_F7         XK_F7
#define KEY_F8         XK_F8
#define KEY_F9         XK_F9
#define KEY_F10        XK_F10
#define KEY_NUMLOCK    XK_Num_Lock
#define KEY_SCRLOCK    XK_Scroll_Lock
#define KEY_HOME       XK_Home
#define KEY_UP         XK_Up
#define KEY_PGUP       XK_Page_Up
#define KEY_GREY_MINUS XK_KP_Subtract
#define KEY_LEFT       XK_Left
#define KEY_PAD_1      XK_KP_1
#define KEY_PAD_2      XK_KP_2
#define KEY_PAD_3      XK_KP_3
#define KEY_PAD_4      XK_KP_4
#define KEY_PAD_5      XK_KP_5
#define KEY_PAD_6      XK_KP_6
#define KEY_PAD_7      XK_KP_7
#define KEY_PAD_8      XK_KP_8
#define KEY_PAD_9      XK_KP_9
#define KEY_PAD_0      XK_KP_0
#define KEY_PAD_DOT    XK_KP_Decimal
#define KEY_ENTER      XK_KP_Enter
#define KEY_RIGHT      XK_Right
#define KEY_GREY_PLUS  XK_KP_Add
#define KEY_END        XK_End
#define KEY_DOWN       XK_Down
#define KEY_PGDN       XK_Page_Down
#define KEY_INSERT     XK_Insert
#define KEY_DEL        XK_Delete
#define KEY_F11        XK_F11
#define KEY_F12        XK_F12
#define KEY_PAUSE      XK_Pause
#endif

#define CHAR_DEL	128
#define CHAR_BACKSP	'\b'
#define CHAR_ESC	'\e'
#define CHAR_LEFT	129
#define CHAR_RIGHT	130
#define CHAR_UP		131
#define CHAR_DOWN	132
#define CHAR_END	133
#define CHAR_HOME	134
#define CHAR_PGUP	135
#define CHAR_PGDN	136
#define CHAR_INSERT	137
#endif
