#!/bin/sh
#echo -s -Wall
#echo -O6 -s -Wall -ffast-math -fomit-frame-pointer
echo -O6 -s -mpentiumpro -march=pentiumpro -malign-double -mstack-align-double -funroll-all-loops -Os -fno-exceptions -fno-rtti -Wall -ffast-math -fomit-frame-pointer
#echo -O3 -ffast-math -pg -a -g -Wall
