#!/bin/sh
#echo -s -Wall
#echo -g -Wall
echo -ggdb -Wall
#echo -O2 -s -Wall -mpentiumpro -march=pentiumpro -malign-double -Os -fno-exceptions -fno-rtti -ffast-math -fomit-frame-pointer
#echo -O6 -s -Wall -ffast-math -fomit-frame-pointer
#echo -O6 -s -Wall -mpentiumpro -march=pentiumpro -malign-double -mstack-align-double -funroll-all-loops -Os -fno-exceptions -fno-rtti -ffast-math -fomit-frame-pointer
#echo -O6 -s -Wall -mpentiumpro -march=pentiumpro -malign-double -funroll-all-loops -Os -fno-exceptions -fno-rtti -ffast-math -fomit-frame-pointer
#echo -O3 -ffast-math -pg -a -g -Wall

